name: Procesar Sentencia Individual
on:
  workflow_dispatch:
    inputs:
      archivo:
        description: 'Nombre del archivo JSON a procesar'
        required: true
        default: 'p_0004_2024_02_05.json'

jobs:
  convertir:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Instalar herramientas
        run: sudo apt-get update && sudo apt-get install -y poppler-utils
        
      - name: Ejecutar script
        env:
          ARCHIVO_A_PROCESAR: ${{ github.event.inputs.archivo }}
        run: python3 script_conversor.py
