name: Procesar Sentencias
on:
  push:
    paths:
      - 'prueba.json'
  workflow_dispatch:

jobs:
  convertir:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Instalar herramientas
        run: sudo apt-get update && sudo apt-get install -y poppler-utils
        
      - name: Ejecutar script
        run: python3 script_conversor.py
